### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by teaddicted** [KieranLitschel/OpenImagesV5Tools#1]
Hey,

Looks like a useful repo. Can you please guide how to use it to download images and annotations of a single or a few classes only?

Thanks

**Comment by KieranLitschel** [comment]
Thanks for your interest, I'm still finalizing a couple of things, as I'm in the process of adding support for bounding boxes, which is going to involve changing the code quite a bit. Once I've done that though I'll be sure to add some documentation of how to use it. I'll close this issue when I've done this, hopefully it'll only take a couple days

**Comment by KieranLitschel** [comment]
I've now added further documentation, with some example code
